[build]
  command = "npm run build"  # Bygger projektet med npm
  publish = "build"  # Uppdaterat till "build" eftersom Next.js sparar där i produktion

[build.environment]
  NEXT_RUNTIME = "edge"  # För bättre Next.js-support i Netlify

[[plugins]]
  package = "@netlify/plugin-nextjs"
